#!/usr/bin/env python

import textwrap
import sys

def get_level(text):
    level = 0
    lastqpos = 0
    for pos in range(0, len(text)):
        if text[pos] == ">":
            level += 1
            lastqpos = pos+1
            if text[pos+1] == " ":
                lastqpos += 1
        elif text[pos] == " ":
            continue
        else:
            break
    return (level, text[lastqpos:-1])
    

def get_prefix(level):
    prefix = (">"*level)
    if level != 0:
        prefix += " "
    return prefix


text = []
level = 0
for line in sys.stdin:
    (nlevel, clean) = get_level(line)
    if len(clean) < 80-level-1:
        if len(text) != 0:
            prefix = get_prefix(level)
            for line in textwrap.wrap("".join(text), width=80, replace_whitespace=False, break_long_words=False, drop_whitespace=True):
                print(prefix + line)
            text = []
        print(get_prefix(nlevel) + clean)
        level = nlevel
    elif nlevel == level:
        text += [clean]
    else:
        prefix = get_prefix(level)
        for line in textwrap.wrap("".join(text), width=80, replace_whitespace=False, break_long_words=False, drop_whitespace=True):
            print(prefix + line)
        level = nlevel
        text = [clean]
